Handle malformed authentication requests more graceful
We see a lot
    uid, secret = encoded.decode('base64').split(':', 1)
    ValueError: need more than 1 value to unpack

which is hard to debug - for the Server and the client. This patch
throws a proper exception presenting the caller some indication
what is wrong.

Change-Id: I66ccf26f4b8fb0b53b3d36197ae53e44ede57715